export enum FlightStatusModel {
  DEPARTED = "DEPARTED",
  CANCELED = "CANCELED",
  LANDED = "LANDED",
  SCHEDULED ="SCHEDULED",
  CHECK_IN = "CHECK_IN",
  BOARDING = "BOARDING",
  EXPECTING = "EXPECTING",
  DELAYED = "DELAYED",
  REDIRECTED = "REDIRECTED"
}
